module.exports = {
	MIN_PLAYER_BUTTON_CLICKED : "MIN_PLAYER_BUTTON_CLICKED",
	NOTIFICATION_EVENT : "NOTIFICATION_EVENT",
	TRACK_CHANGED_UPDATE : "TRACK_CHANGED_UPDATE",
	NO_PLAY_STUFF : "NO_PLAY_STUFF"
};