module.exports = {
	MINI_MUSIC_DETAILS: "MINI_MUSIC_DETAILS",
	MINI_PLAYER_EVENTS: "MINI_PLAYER_EVENTS",
	SHOW_MINI_PLAYER: "SHOW_MINI_PLAYER",
	UPDATE_MINI_PLAYER: "UPDATE_MINI_PLAYER",
	MINIMIZE_WINDOW: "MINIMIZE_WINDOW",
	MAXIMIZE_WINDOW: "MAXIMIZE_WINDOW",
	CLOSE_WINDOW: "CLOSE_WINDOW",
	OPEN_BROWSER_WINDOW: "OPEN_BROWSER_WINDOW",
	CONTROL_EVENT_OCCURED: "CONTROL_EVENT_OCCURED",
	NOTIFICATION_OCCURED: "NOTIFICATION_OCCURED"
};